/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 2
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "/home/votre_user/maps/carte_complete.pcd"  # CHANGÉ: chemin absolu
        common:
            lid_topic:  "/velodyne_points"
            imu_topic:  "/imu/data"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0
        preprocess:
            lidar_type: 1
            scan_line: 16
            scan_rate: 10
            timestamp_unit: 2
            blind: 2.0
        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 50.0
            extrinsic_est_en: false
            extrinsic_T: [ 0., 0., 0.28]
            extrinsic_R: [ 1., 0., 0., 
                        0., 1., 0., 
                        0., 0., 1.]
        publish:
            path_en: true                    # CHANGÉ: activé pour voir la trajectoire
            scan_publish_en: true
            dense_publish_en: true           # CHANGÉ: activé pour une carte plus dense
            scan_bodyframe_pub_en: false     # CHANGÉ: false pour avoir les points dans le repère global
        pcd_save:
            pcd_save_en: true                # CHANGÉ: ACTIVÉ !
            interval: -1
