controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["base_front_left_wheel_joint", "base_back_left_wheel_joint"]
      right_wheel_names: ["base_front_right_wheel_joint", "base_back_right_wheel_joint"]
      wheel_separation: 0.45
      wheel_radius: 0.1
      publish_rate: 50
      use_stamped_vel: false
